#!/usr/bin/env bash

# This file is part of the ArchyPie project.
#
# Please see the LICENSE file at the top-level directory of this distribution.

## config / defaults
user="USERTOBECHOSEN"

home="$(eval echo ~${user})"
archypie_path="$home/ArchyPie"

usb_path="$UM_MOUNTPOINT/archypie-mount"

## internals
hook_name=${0##*/}

## functions
function log() {
    logger -p user.$1 -t usbmount-"$hook_name"-[$$] -- "$2"
}

function log_cmd() {
    local ret
    local error
    error="$("$@" 2>&1 >/dev/null)"
    ret=$?
    [[ "$ret" -ne 0 ]] && log err "$* - returned $ret - $error"
}

## some sanity checking
if [[ -z "$UM_MOUNTPOINT" ]]; then
    log err "UM_MOUNTPOINT not set!"
    exit 0
fi

if [[ ! -d "$UM_MOUNTPOINT" ]]; then
    log err "UM_MOUNTPOINT is not a directory"
    exit 0
fi

# check for a archypie-mount folder
if [[ ! -d "$usb_path" ]]; then
    exit 0
fi

if [[ -z "$(ls -A "$usb_path")" ]]; then
    log info "Copying existing $archypie_path to $usb_path ..."
    log_cmd rsync -rtu "$archypie_path/" "$usb_path/"
fi

log info "Mounting $usb_path over $archypie_path ..."
log_cmd mount -o bind "$usb_path" "$archypie_path"
